Purple Buzz/Entities/BaseEntity.cs
namespace Purple_Buzz.Entities;

public class BaseEntity
{
    public int Id { get; set; }
    public DateTime CreatedDate { get; set;}
    public DateTime? ModifiedDate { get; set;}
}

Purple Buzz/Entities/Service.cs
namespace Purple_Buzz.Entities;

public class Service:BaseEntity
{
    public string Name {  get; set; }
    public string Description { get; set; }
    public string PhotoPath { get; set; }
    public string Type { get; set; }

}

Purple Buzz/Models/About/AboutIndexVM.cs
namespace Purple_Buzz.Models.About;

public class AboutIndexVM
{
    public List<TeamMemberVM> TeamMembers { get; set; }
}

Purple Buzz/Models/About/TeamMemberVM.cs
namespace Purple_Buzz.Models.About;

public class TeamMemberVM
{
    public string PhotoPath { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Position { get; set; }

}

Purple Buzz/Models/Home/HomeIndexVM.cs
namespace Purple_Buzz.Models.Home;

public class HomeIndexVM
{
    public List<ServiceVM> Services { get; set; }

}

Purple Buzz/Models/Home/ServiceVM.cs
namespace Purple_Buzz.Models.Home;

public class ServiceVM
{
    public string Name { get; set; }
    public string Description { get; set; }
    public string PhotoPath { get; set; }
    public string Type {  get; set; }
}

Purple Buzz/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Purple_Buzz.Models.About;

namespace Purple_Buzz.Controllers;

public class AboutController : Controller
{
    public IActionResult Index()
    {
        var model = new AboutIndexVM
        {

            TeamMembers = new List<TeamMemberVM>
            {
            new TeamMemberVM {Name="John", Surname="Doe", Position="Business Development", PhotoPath="/assets/img/team-01.jpg"},
            new TeamMemberVM {Name="John", Surname="Doe", Position="Business Development", PhotoPath="/assets/img/team-02.jpg"},
            new TeamMemberVM {Name="John", Surname="Doe", Position="Developer", PhotoPath="/assets/img/team-03.jpg"}

            }
        };
        return View(model);
    }
}

Purple Buzz/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Purple_Buzz.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Purple Buzz/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Purple_Buzz.Data;
using Purple_Buzz.Models.Home;

namespace Purple_Buzz.Controllers;

public class HomeController : Controller
{
    private readonly AppDbContext _context;
    public HomeController(AppDbContext context)
    {
        _context = context;

    }
    public IActionResult Index()
    {
        var services = _context.Services.ToList();
        var servicesList = new List<ServiceVM>();
        foreach (var service in services)
        {
            var serviceVM = new ServiceVM{
                Name = service.Name,
                Description = service.Description,
                PhotoPath = service.PhotoPath,
                Type= service.Type
            };
            servicesList.Add(serviceVM);
        }
        var model = new HomeIndexVM
        {
            Services = servicesList
        };
        return View(model);
    }
}

Purple Buzz/Controllers/PricingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Purple_Buzz.Controllers
{
    public class PricingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Purple Buzz/Controllers/WorkController.cs
using Microsoft.AspNetCore.Mvc;

namespace Purple_Buzz.Controllers
{
    public class WorkController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }
        public IActionResult Details() {
            return View();
        }
    }
}

Purple Buzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Purple Buzz HTML Template with Bootstrap 5 Beta 1</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="~/assets/img/apple-icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.ico">
    <!-- Load Require CSS -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font CSS -->
    <link href="~/assets/css/boxicon.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <!-- Load Tempalte CSS -->
    <link rel="stylesheet" href="~/assets/css/templatemo.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/assets/css/custom.css">
    <!--

    TemplateMo 561 Purple Buzz

    https://templatemo.com/tm-561-purple-buzz

    -->
</head>

<body>
    <!-- Header -->
    <nav id="main_nav" class="navbar navbar-expand-lg navbar-light bg-white shadow">
        <div class="container d-flex justify-content-between align-items-center">
            <a class="navbar-brand h1" asp-controller="Home" asp-action="Index">
                <i class='bx bx-buildings bx-sm text-dark'></i>
                <span class="text-dark h4">Purple</span> <span class="text-primary h4">Buzz</span>
            </a>
            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-toggler-success" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="navbar-toggler-success">
                <div class="flex-fill mx-xl-5 mb-2">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-xl-5 text-center text-dark">
                        <li class="nav-item">
                            <a class="nav-link btn-outline-primary rounded-pill px-3" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn-outline-primary rounded-pill px-3" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn-outline-primary rounded-pill px-3" asp-controller="Work" asp-action="Index">Work</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn-outline-primary rounded-pill px-3" asp-controller="Pricing" asp-action="Index">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn-outline-primary rounded-pill px-3" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar align-self-center d-flex">
                    <a class="nav-link" href="#"><i class='bx bx-bell bx-sm bx-tada-hover text-primary'></i></a>
                    <a class="nav-link" href="#"><i class='bx bx-cog bx-sm text-primary'></i></a>
                    <a class="nav-link" href="#"><i class='bx bx-user-circle bx-sm text-primary'></i></a>
                </div>
            </div>
        </div>
    </nav>
    <!-- Close Header -->
    @RenderBody()
    <!-- Start Footer -->
    <footer class="bg-secondary pt-4">
        <div class="container">
            <div class="row py-4">

                <div class="col-lg-3 col-12 align-left">
                    <a class="navbar-brand" href="index.html">
                        <i class='bx bx-buildings bx-sm text-light'></i>
                        <span class="text-light h5">Purple</span> <span class="text-light h5 semi-bold-600">Buzz</span>
                    </a>
                    <p class="text-light my-lg-4 my-2">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt ut.
                    </p>
                    <ul class="list-inline footer-icons light-300">
                        <li class="list-inline-item m-0">
                            <a class="text-light" target="_blank" href="http://facebook.com/">
                                <i class='bx bxl-facebook-square bx-md'></i>
                            </a>
                        </li>
                        <li class="list-inline-item m-0">
                            <a class="text-light" target="_blank" href="https://www.linkedin.com/">
                                <i class='bx bxl-linkedin-square bx-md'></i>
                            </a>
                        </li>
                        <li class="list-inline-item m-0">
                            <a class="text-light" target="_blank" href="https://www.whatsapp.com/">
                                <i class='bx bxl-whatsapp-square bx-md'></i>
                            </a>
                        </li>
                        <li class="list-inline-item m-0">
                            <a class="text-light" target="_blank" href="https://www.flickr.com/">
                                <i class='bx bxl-flickr-square bx-md'></i>
                            </a>
                        </li>
                        <li class="list-inline-item m-0">
                            <a class="text-light" target="_blank" href="https://www.medium.com/">
                                <i class='bx bxl-medium-square bx-md'></i>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-4 my-sm-0 mt-4">
                    <h3 class="h4 pb-lg-3 text-light light-300">
                        Our Company</h2>
                        <ul class="list-unstyled text-light light-300">
                            <li class="pb-2">
                                <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light" href="index.html">Home</a>
                            </li>
                            <li class="pb-2">
                                <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="about.html">About Us</a>
                            </li>
                            <li class="pb-2">
                                <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="work.html">Work</a>
                            </li>
                            <li class="pb-2">
                                <i class='bx-fw bx bxs-chevron-right bx-xs'></i></i><a class="text-decoration-none text-light py-1" href="pricing.html">Price</a>
                            </li>
                            <li class="pb-2">
                                <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="contact.html">Contact</a>
                            </li>
                        </ul>
                </div>

                <div class="col-lg-3 col-md-4 my-sm-0 mt-4">
                    <h2 class="h4 pb-lg-3 text-light light-300">Our Works</h2>
                    <ul class="list-unstyled text-light light-300">
                        <li class="pb-2">
                            <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="#">Branding</a>
                        </li>
                        <li class="pb-2">
                            <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="#">Business</a>
                        </li>
                        <li class="pb-2">
                            <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="#">Marketing</a>
                        </li>
                        <li class="pb-2">
                            <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="#">Social Media</a>
                        </li>
                        <li class="pb-2">
                            <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="#">Digital Solution</a>
                        </li>
                        <li class="pb-2">
                            <i class='bx-fw bx bxs-chevron-right bx-xs'></i><a class="text-decoration-none text-light py-1" href="#">Graphic</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-4 my-sm-0 mt-4">
                    <h2 class="h4 pb-lg-3 text-light light-300">For Client</h2>
                    <ul class="list-unstyled text-light light-300">
                        <li class="pb-2">
                            <i class='bx-fw bx bx-phone bx-xs'></i><a class="text-decoration-none text-light py-1" href="tel:010-020-0340">010-020-0340</a>
                        </li>
                        <li class="pb-2">
                            <i class='bx-fw bx bx-mail-send bx-xs'></i><a class="text-decoration-none text-light py-1" href="mailto:info@company.com">info@company.com</a>
                        </li>
                    </ul>
                </div>

            </div>
        </div>

        <div class="w-100 bg-primary py-3">
            <div class="container">
                <div class="row pt-2">
                    <div class="col-lg-6 col-sm-12">
                        <p class="text-lg-start text-center text-light light-300">
                            © Copyright 2021 Purple Buzz Company. All Rights Reserved.
                        </p>
                    </div>
                    <div class="col-lg-6 col-sm-12">
                        <p class="text-lg-end text-center text-light light-300">
                            Designed by <a rel="sponsored" class="text-decoration-none text-light" href="https://templatemo.com/" target="_blank"><strong>TemplateMo</strong></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <!-- End Footer -->
    <!-- Bootstrap -->
    <script src="~/assets/js/bootstrap.bundle.min.js"></script>
    <!-- Load jQuery require for isotope -->
    <script src="~/assets/js/jquery.min.js"></script>
    <!-- Isotope -->
    <script src="~/assets/js/isotope.pkgd.js"></script>
    <!-- Page Script -->
    <script>
        $(window).load(function () {
            // init Isotope
            var $projects = $('.projects').isotope({
                itemSelector: '.project',
                layoutMode: 'fitRows'
            });
            $(".filter-btn").click(function () {
                var data_filter = $(this).attr("data-filter");
                $projects.isotope({
                    filter: data_filter
                });
                $(".filter-btn").removeClass("active");
                $(".filter-btn").removeClass("shadow");
                $(this).addClass("active");
                $(this).addClass("shadow");
                return false;
            });
        });
    </script>
    <!-- Templatemo -->
    <script src="~/assets/js/templatemo.js"></script>
    <!-- Custom -->
    <script src="~/assets/js/custom.js"></script>

</body>

</html>

Purple Buzz/Views/Work/Index.cshtml
    <!-- Start Banner Hero -->
<div id="work_banner" class="banner-wrapper bg-light w-100 py-5">
    <div class="banner-vertical-center-work container text-light d-flex justify-content-center align-items-center py-5 p-0">
        <div class="banner-content col-lg-8 col-12 m-lg-auto text-center">
            <h1 class="banner-heading h2 display-3 pb-5 semi-bold-600 typo-space-line-center">Our Work</h1>
            <h3 class="h4 pb-2 regular-400">Elit, sed do eiusmod tempor incididunt</h3>
            <p class="banner-body pb-2 light-300">
                Vector illustration <a class="text-white" href="http://freepik.com/" target="_blank">Freepik</a>.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna
                aliqua. Quis ipsum suspendisse ultrices gravida. Risus
                commodo viverra maecenas accumsan lacus.
            </p>
            <button type="submit" class="btn rounded-pill btn-outline-light px-4 me-4 light-300">Learn More</button>
            <button type="submit" class="btn rounded-pill btn-secondary text-light px-4 light-300">Contact Us</button>
        </div>
    </div>
</div>
<!-- End Banner Hero -->
<!-- Start Our Work -->
<section class="container py-5">
    <div class="row justify-content-center my-5">
        <div class="filter-btns shadow-md rounded-pill text-center col-auto">
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4 active" data-filter=".project" href="#">All</a>
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4" data-filter=".business" href="#">Business</a>
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4" data-filter=".marketing" href="#">Marketing</a>
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4" data-filter=".social" href="#">Social Media</a>
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4" data-filter=".graphic" href="#">Graphic</a>
        </div>
    </div>

    <div class="row projects gx-lg-5">
        <a asp-controller="Work" asp-action="Details" class="col-sm-6 col-lg-4 text-decoration-none project marketing social business">
            <div class="service-work overflow-hidden card mb-5 mx-5 m-sm-0">
                <img class="card-img-top" src="~/assets/img/our-work-01.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Digital Marketing</h5>
                    <p class="card-text light-300 text-dark">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt ut labore et dolor.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="Work" asp-action="Details" class="col-sm-6 col-lg-4 text-decoration-none project graphic social">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/assets/img/our-work-02.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Corporate Branding</h5>
                    <p class="card-text light-300 text-dark">
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="Work" asp-action="Details" class="col-sm-6 col-lg-4 text-decoration-none project marketing graphic business">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/assets/img/our-work-03.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Leading Digital Solution</h5>
                    <p class="card-text light-300 text-dark">
                        Duis aute irure dolor in reprehenderit in voluptate velit
                        esse cillum dolore eu fugiatdolore eu fugiat nulla pariatur.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="Work" asp-action="Details" class="col-sm-6 col-lg-4 text-decoration-none project social business">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/assets/img/our-work-04.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Smart Applications</h5>
                    <p class="card-text light-300 text-dark">
                        Excepteur sint occaecat cupidatat non proident, sunt in
                        culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="Work" asp-action="Details" class="col-sm-6 col-lg-4 text-decoration-none project marketing">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/assets/img/our-work-05.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Corporate Stationary</h5>
                    <p class="card-text light-300 text-dark">
                        Excepteur sint occaecat cupidatat non proident,
                        sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="Work" asp-action="Details" class="col-sm-6 col-lg-4 text-decoration-none project marketing graphic">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/assets/img/our-work-06.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">8 Financial Tips</h5>
                    <p class="card-text light-300 text-dark">
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
    </div>
    <div class="row">
        <div class="btn-toolbar justify-content-center pb-4" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group me-2" role="group" aria-label="First group">
                <button type="button" class="btn btn-secondary text-white">Previous</button>
            </div>
            <div class="btn-group me-2" role="group" aria-label="Second group">
                <button type="button" class="btn btn-light">1</button>
            </div>
            <div class="btn-group me-2" role="group" aria-label="Second group">
                <button type="button" class="btn btn-secondary text-white">2</button>
            </div>
            <div class="btn-group" role="group" aria-label="Third group">
                <button type="button" class="btn btn-secondary text-white">Next</button>
            </div>
        </div>
    </div>
</section>
<!-- End Our Work -->
<!-- Start Feature Work -->
<section class="bg-light py-5">
    <div class="feature-work container my-4">
        <div class="row d-flex d-flex align-items-center">
            <div class="col-lg-5">
                <h3 class="feature-work-title h4 text-muted light-300">Featured Work</h3>
                <h1 class="feature-work-heading h2 py-3 semi-bold-600">Transform with us</h1>
                <p class="feature-work-body text-muted light-300">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse
                    ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.
                </p>
                <p class="feature-work-footer text-muted light-300">
                    Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur.
                </p>
            </div>
            <div class="col-lg-6 offset-lg-1 align-left">
                <div class="row">
                    <a class="col" data-type="image" data-fslightbox="gallery" href="~/assets/img/feature-work-1-large.jpg">
                        <img class="img-fluid" src="~/assets/img/feature-work-1.jpg">
                    </a>
                    <a class="col" data-type="image" data-fslightbox="gallery" href="~/assets/img/feature-work-2-large.jpg">
                        <img class="img-fluid" src="~/assets/img/feature-work-2.jpg">
                    </a>
                </div>
                <div class="row pt-4">
                    <a class="col" data-type="image" data-fslightbox="gallery" href="~/assets/img/feature-work-3-large.jpg">
                        <img class="img-fluid" src="~/assets/img/feature-work-3.jpg">
                    </a>
                    <a class="col" data-type="image" data-fslightbox="gallery" href="~/assets/img/feature-work-4-large.jpg">
                        <img class="img-fluid" src="~/assets/img/feature-work-4.jpg">
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>